# Generated by Django 5.1.2 on 2024-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('file', models.FileField(upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery/thumbnails/')),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='media_items', to='Events.gallerycategory')),
            ],
            options={
                'ordering': ['-event_date', 'order'],
            },
        ),
    ]
