# Generated by Django 5.1.2 on 2024-11-06 12:44

import Portfolio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('order', models.IntegerField(default=0, help_text='Order in which category appears')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False, help_text='Feature this project in listings')),
                ('image', models.ImageField(blank=True, help_text='Supported formats: jpg, png, gif', null=True, upload_to='projects/images/')),
                ('video', models.FileField(blank=True, help_text='Supported formats: mp4, webm, mov', null=True, upload_to='projects/videos/', validators=[Portfolio.models.validate_video_extension])),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('video_duration', models.DurationField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Portfolio.projectcategory')),
            ],
            options={
                'ordering': ['-featured', '-created_date'],
            },
        ),
    ]
